######### Application Access Point ########
#
#server:
#    address: localhost
#    port: 8086
#    #contextPath: /
#
#management:
#    port: 8087
#    #contextPath: /manage
#
#
######### Database Access Point ########
#
#    #url: jdbc:mysql://localhost:3306/ordersnapp3
#    #username: root
#    #password: admin
#
#spring.datasource:
#    url: jdbc:mysql://localhost:3306/chitfunds
#    username: root
#    password: 12345
#    driverClassName: com.mysql.jdbc.Driver
#spring.jpa.generate-ddl: true
#spring.jpa.hibernate.ddl-auto: update
#spring.jpa.open-in-view: true
#spring.jpa.show-sql: true
#
#logging:
#  level:
#    root: ERROR
#    org.springframework: ERROR
#    com.fastxpo: DEBUG
#    org.hibernate: ERROR